version: '3.8'

services:
  # Main LLM serving service (CPU mode)
  llm-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: llm-serving
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=${MODEL_NAME:-gpt2}
      - TENSOR_PARALLEL_SIZE=1
      - QUANTIZATION_MODE=none
      - MAX_BATCH_SIZE=32
      - GPU_MEMORY_UTILIZATION=0.0
    volumes:
      - ./models:/models
      - ./logs:/app/logs
      - huggingface_cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  huggingface_cache:
  prometheus_data:
  grafana_data:
