global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'llm-serving-monitor'

scrape_configs:
  - job_name: 'llm-server'
    static_configs:
      - targets: ['llm-server:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files
rule_files:
  - 'alerts.yml'
